language: node_js
node_js:
- '6'
after_success:
- coveralls < coverage/report-lcov/lcov.info
before_deploy:
- git config --global user.email ${EMAIL}
- git config --global user.name ${USER}
- git config --global push.default matching
deploy:
  provider: npm
  email: "$EMAIL"
  api_key: "$NPM_API_KEY"
  skip_cleanup: true
  on:
    repo: mvallim/javascript-multipart-file-upload
    node: '6'
    tags: true
env:
  global:
  - secure: CsoSdx5fpvW8ivKLGBqGpWS49H5GljdZy7/7z69jjwcN0haoBoum5mawRXNW7W7EUQLMqNqmcccpKBwoLwteGzGljmjDeFZIgLqbmzkkjfvX0gFLM6LEUZXr1uYDk7ENsafE/+COAyeCbkdigV0RSie/R+gXhLKS4aXhZPZfsLoXpUwH8zbvZEaKxmVZbY/nUg5uMH7+6EEQAHZ6a00TAK+xnP49IjSGICc8VtH6AFsStLluh482W6CYPMCGKgvbkFKvEPUJQ/iD58EoEAo3JZTM+zuUYo11QwHIj3tpvV9symFEZ9qi7LJYFEnvMsn8q7TGOacL1Kj2C9wxDma8/RlxiFUTXB/jGxNoazHi+eAAobyQttr2/RWjahJ0B5wsd/7DG0WzGRRFg0rugoOWOtFKqPwhFhCpM7V38XoMqAtVYplc2MxIFZQoyYXSXQX06ld/tyxnk3Qd2cDshnsN9p3WLzieZcjJnJyat1JmLUKR10IN07+7mmMcBHhyPjyh/u0zuC7HwEA2JuM282pnkTTJIUC1xNRnroPjzzNjDpt12QscoDSVpjYBQuVXoM/WDqxL5G45bwwsM1NpfALYgTEidtuMuV2K6SnbMhs5XfRjj9Biazj39SwCyKHXKzks6Rj6X/olANdk7goDOTjH1F+Al1MeFfKvz7TaCs8Ndho=
  - secure: mk6X3DYN598Fq0AUssNAOIEmSLKr2BSAMFPwhg/eHsY7E5t17g7EMYd8eJ3gVO3hAdEw3WStsxwHVimbeEkKpOzYTbWN1bu9jK41gBEi2kLr6sZCE8xFs4APem1MFEXSolBAzKbuXySVI/f+zuAxo6yxvNGqlSUR4dxkHI36fbalk/7ioCUv2VQhrnog59NpOEeyg3purnOPwFPBASjq+M5tjAl8dI+l5oy1P5iex8VZj2s1vYCGITPX+nlqK7rLk7igAZbd/4dchTlRoC/q0Aw83AKD/AJNBIqvL2OMbGLUhWmUq1MVezrLraZgoebD2JRzhTmTvfChA6YrYvJ0SuN6EYbVr6dO/rbnoElz03ZyRG0wsvYSeZyFSq/ldfDpMROaGuH0WA12KjAt1fCPd9XE5sOPlzXlFbRte5DcrRzl+UGSPSOW3aGtK7SQdgj+IR9A7M/NgNZarV57Rrwf7N6pxSaEtEAIhjKdbW9tFniRa6+JBQAh1aiSLrSPJKBrUb1CbQZTWcgUBOB2Mx4bASWufG2oqH1AhSXLso6vhSWCiDyBa8XLFZtS7X06rK+BLK7DwzH2HUoV8c2VeBj3EM45lco+vPxW5rhiYA5+9/4HTElme8FhOCUN/3fe+nLnuAuo+j3YQEpIBBnO5HQydYDdwedb3NNBJeHy5Urk0Lg=
  - secure: HfGJNjaxEpLSatuBGhLrFWpQbkb5q50GkBOFDRwDaacTwFs4Se+VFWzfNqnuPTtkGerObln8iokKJ65wllXKJtxfY/SJGWkC5YCbZB39r3jC3Io3ASyQslH5NtnQWMEk8KHUX3XKOvmdgiNHbJRbWrh+Os0uh07W1WXzoaNmST26e5TN+oDwW2wu+i/1WIgvzyc2uETnGOJswCh5/iap+0/3vLSRRA3ibHkD2so4vcaBWKs6TtqnUgGepuzsGfmUsl1MI60vRyK9oZlrG0UO/yJc3sRyq0O3Vh3SzEwy6AS7yytixuYT5amo6p+Q8Zp2cLCvoCbJIYSuNInWZzOKE4GBQxeUHIgmV4mMtKmr8yUKZsgHbDmFcSZxmtlU5Dn7lPq23UYMkdMQ0MUOoWFe1RDAQZJnrI+p+zpmthT9SuA5ace0cRGyCs09GwiVzYzQGmXQlKO/b5OegbuP28jbjkROX9CyzQ7LXtDD5RQmCMOTqEty8Fu7BCLKyBeGdY1/ID9VYztjZBQwn/ui1mcBnI+HzIvIQPiLh1JnwDDn6OJSq1zgmgH8+dsE7jZh09RdMYZP1USA2Chijfl45XK+q1NFzcicSrSLi7GDR5RP1i72GLWTB3jR8sAJRzwISoDoUrf1R3J1tu42aB28HpYINJk2Y37z4OxHOTNE4KilFsM=
